name: Build GCCLIB

on: [push]

jobs:

#**************************************************#
  build-cms:
    name: Build for CMS
    runs-on: [ubuntu-latest]
    container: adriansutherland/vm370:builder

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Move Source
      run: |
        mkdir /opt/hercules/vm370/io
        mv * /opt/hercules/vm370/io
      shell: bash

    - name: Build
      working-directory: /opt/hercules/vm370
      run: |
        chmod -R ugo+rw *
        hercules -f hercules.conf -d >/dev/null 2>/dev/null &
        cd io
        chmod +x cmsbuild.sh
        echo "Running CMSBUILD"
        ./cmsbuild.sh
      shell: bash

    - name: Get Executable
      run: |
        mkdir -p exe
        cp /opt/hercules/vm370/io/gcclibbin.aws exe
        cp /opt/hercules/vm370/io/gcclibsrc.aws exe
        cp /opt/hercules/vm370/io/gcclibbin.vmarc exe
        cp /opt/hercules/vm370/io/gcclibsrc.vmarc exe
        cp /opt/hercules/vm370/io/LICENSE exe
        cp /opt/hercules/vm370/io/README.md exe
        cp /opt/hercules/vm370/io/changelog.txt exe
        chmod -R ugo+r exe
      shell: bash

    - name: Upload Executable
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-artifact@v1
      with:
        name: GCCLIB
        path: ./exe

#**************************************************#
  release:
    if: startsWith(github.ref, 'refs/tags/')
    name: Release
    needs: [build-cms]
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1

      - name: Get CMS binary
        uses: actions/download-artifact@v1
        with:
          name: GCCLIB

      - name: ZIP CMS binary
        run:
          zip -r GCCLIB.zip GCCLIB

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: true

      - name: Upload Release Asset - CMS
        id: upload-release-asset-CMS
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./GCCLIB.zip
          asset_name: GCCLIB.zip
          asset_content_type: application/zip
